### ISSUE TITLE
Request: option to keep control genes in 'runLimmaAnalysis'

### ISSUE THREAD

**Issue by hendrikweisser** [calebclass/NanoTube#1]
First, thanks for making this package available!

For some QC applications (e.g. MA plots) and comparisons to other methods, it can be useful to see what happens to the control genes (positive, negative, housekeeping) during differential expression analysis. Currently these genes are removed in `runLimmaAnalysis`:
https://github.com/calebclass/NanoTube/blob/026563de287e07507f9ee6999d9fd25a9ac08663/R/runLimmaAnalysis.R#L51-L54

Would it be possible to add an option to `runLimmaAnalysis` to keep the control genes (and process them like the rest)?

**Comment by calebclass** [comment]
@hendrikweisser So sorry for the delay!  I think I've resolved this.  Please let me know if you have any trouble.
