### ISSUE TITLE
Request:  Allow for RCC file names as input to processNanostringData

### ISSUE THREAD

**Issue by genec1** [calebclass/NanoTube#2]
`processNanostringData` doesn't currently allow for RCC file names to be supplied as input (it does file directories, txt files, csv files, etc).  A simple edit to the function allows for this extra flexibility:

```
		colnames(dat$dict) <- gsub("\\.| ", "", colnames(dat$dict))
	}
	else if (file.extension %in% c(".RCC", ".rcc")) {
		fileNames <- nsFiles[ grep("\\.rcc$", tolower(nsFiles)) ]
		cat("\nReading in .RCC files......", file = logfile, 
			append = TRUE)
		dat <- read_merge_rcc(fileNames, includeQC, logfile)
	}
	else {
		if (file.extension %in% c(".zip", ".ZIP")) {
```

**Comment by calebclass** [comment]
Thanks for this suggestion! Looks like everything is working, please let me know if any trouble pops up.
